/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zZ7PUrpEMh4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Main1() {
  return (
    (<div className="flex min-h-screen flex-col bg-background w-full">
      <header className="sticky top-0 z-40 w-full border-b bg-background">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="font-bold">Shade Tech</span>
          </Link>
          <nav className="hidden space-x-4 md:flex">
            <Link href="#" className="hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Documentation
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Resources
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="outline" size="sm" className="md:hidden">
            <MenuIcon className="h-5 w-5" />
            <span className="sr-only">Toggle Menu</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section
          className="bg-gradient-to-r from-primary to-secondary py-20 text-primary-foreground align-middle justify-center">
          <div
            className="container flex flex-col items-center justify-center gap-6 px-4 md:px-6">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">Welcome to Shade Tech</h1>
            <p className="max-w-[700px] text-lg md:text-xl">
              Explore the world of Next.js, JavaScript, coding, and more with our comprehensive documentation.
            </p>
            <Link
              href="https://www.youtube.com/@ShadeTech_"
              className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
              prefetch={false}>
              Watch Videos
            </Link>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <div className="grid gap-8 md:grid-cols-2">
              <div>
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">About Shade Tech</h2>
                <p className="mt-4 text-muted-foreground">
                  Shade Tech is a YouTube channel dedicated to providing high-quality content on Next.js, JavaScript,
                  coding, and various tech-related topics. Our mission is to help developers of all skill levels expand
                  their knowledge and stay up-to-date with the latest trends and best practices in the industry.
                </p>
                <p className="mt-4 text-muted-foreground">
                  Our team of experienced developers and content creators work tirelessly to produce informative and
                  engaging videos that cover a wide range of topics, from beginner-friendly tutorials to advanced
                  techniques and best practices.
                </p>
              </div>
              <div className="flex items-center justify-center">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={400}
                  alt="Shade Tech Team"
                  className="rounded-lg" />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Documentation</h2>
            <p className="mt-4 text-muted-foreground">
              Explore our comprehensive documentation on a variety of topics related to Next.js, JavaScript, coding, and
              more.
            </p>
            <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Next.js Fundamentals</CardTitle>
                  <CardDescription>
                    Learn the basics of Next.js and how to build modern web applications.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Getting Started with Next.js
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        File-based Routing
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Static Site Generation
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Server-side Rendering
                      </Link>
                    </li>
                  </ul>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>JavaScript Essentials</CardTitle>
                  <CardDescription>Dive into the fundamentals of JavaScript and master the language.</CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Variables and Data Types
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Functions and Scope
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Arrays and Objects
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Asynchronous JavaScript
                      </Link>
                    </li>
                  </ul>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Coding Best Practices</CardTitle>
                  <CardDescription>
                    Learn about the best practices and techniques for writing clean, maintainable code.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Code Formatting and Linting
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Modular Design Patterns
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Test-Driven Development
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Debugging and Troubleshooting
                      </Link>
                    </li>
                  </ul>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Resources</h2>
            <p className="mt-4 text-muted-foreground">
              Check out these additional resources to further enhance your learning experience.
            </p>
            <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Recommended Books</CardTitle>
                  <CardDescription>
                    Expand your knowledge with these essential books on Next.js, JavaScript, and more.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        "Next.js in Action" by Evan Bacon
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        "Eloquent JavaScript" by Marijn Haverbeke
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        "Clean Code" by Robert C. Martin
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        "The Pragmatic Programmer" by Andrew Hunt and David Thomas
                      </Link>
                    </li>
                  </ul>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Useful Tools</CardTitle>
                  <CardDescription>
                    Discover the best tools and resources to enhance your development workflow.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Visual Studio Code
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Vercel
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Netlify
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Cypress
                      </Link>
                    </li>
                  </ul>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Relevant Websites</CardTitle>
                  <CardDescription>
                    Explore these websites to stay up-to-date with the latest trends and news in the tech industry.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="space-y-2">
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Next.js Documentation
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        JavaScript.info
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        CSS-Tricks
                      </Link>
                    </li>
                    <li>
                      <Link href="#" className="hover:underline" prefetch={false}>
                        Dev.to
                      </Link>
                    </li>
                  </ul>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-24">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Contact Us</h2>
            <p className="mt-4 text-muted-foreground">Have any questions or feedback? Get in touch with us.</p>
            <form className="mt-8 grid gap-4">
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <Input label="Name" placeholder="Enter your name" />
                <Input label="Email" type="email" placeholder="Enter your email" />
              </div>
              <Textarea label="Message" placeholder="Enter your message" />
              <Button type="submit" className="justify-self-end">
                Submit
              </Button>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-6 text-muted-foreground">
        <div
          className="container flex flex-col items-center justify-between gap-4 px-4 md:flex-row md:px-6">
          <div className="flex items-center gap-2">
            <MountainIcon className="h-6 w-6" />
            <span>Shade Tech</span>
          </div>
          <p className="text-sm">&copy; 2024 Shade Tech. All rights reserved.</p>
        </div>
      </footer>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
